/*@StepGroupList
{
  "groups": [
    "lambda_reg_navigation.sg"
  ]
}
*/

// ************************** IMPORTANT **************************
// This file is auto-generated by PlayQ for Step Group.
// Do not edit it manually. File is auto-generated.
// Any changes done directly will be lost on the next generation.
// ***************************************************************

import { Given } from '@cucumber/cucumber';

Given('Step Group: -lambda_reg_navigation.sg- -Navigating to Lambda Test Registration Page-', async function () {
    /*StepGroup:lambda_reg_navigation.sg
        * Web: Open browser -url: "#{env.lambdatest.registration.url}" -options: ""
        * Web: Verify header -text: "Register Account" -options: ""
        * Comm: Comment -text: "renish123"
    */
});
